server:
  port: 8080
 
spring:
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/job_platform?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
 
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.jobplatform.*.entity
 
#showSql
logging:
  level:
    com:
      example:
        mapper : debug